name: CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [main, development]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm config set "@fortawesome:registry" https://npm.fontawesome.com/
      - run: npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.FONT_AWESOME_PRO_TOKEN }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
