name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Make envfile dashboard
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          envkey_REACT_APP_OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          file_name: ./build/.env

      - name: Use Node.js 16
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build app
        run: |
          npm config set "@fortawesome:registry" https://npm.fontawesome.com/
          npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.FONT_AWESOME_PRO_TOKEN }}
          npm install
          npm run build

      - name: Checkout build
        run: find build/ -print

      - name: Deploy app
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.MASTER_IP }}
          username: ${{ secrets.MASTER_USER }}
          password: ${{ secrets.MASTER_PASSWORD }}
          server-dir: ${{ secrets.MASTER_REMOTE }}
          local-dir: build/
